import { List, Text, Stack } from '@mantine/core';

import './style.css';

const ProductResultsInfo = () => {
	return (
		<Stack gap="sm" className="worldCereal-ProductResultsInfo">
			<Text fw={500} mt="sm" mb={4}>
				Four GeoTiff images will be generated.
			</Text>
			<Text fw={600} mt="sm" mb={4}>
				Each raster contains at least three bands:
			</Text>
			<List type="unordered" spacing="xs" withPadding>
				<List.Item>Band 1: classification – The classification label of the pixel.</List.Item>
				<List.Item>Band 2: confidence – The class-specific probability of the winning class.</List.Item>
				<List.Item>
					Band 3 and beyond: probability_xxx – Class-specific probabilities. The "xxx" indicates the associated class.
				</List.Item>
			</List>
			<Text fw={600} mt="sm" mb={4}>
				The following files will be generated:
			</Text>
			<List type="ordered" spacing="xs" withPadding>
				<List.Item>
					<Text span fw={600}>
						cropland-raw.tif
					</Text>
					<br />
					The original temporary crops mask, generated by the default global WorldCereal temporary crops model. This
					model differentiates temporary crops from all other land cover types.
					<br />
					<Text size="sm" c="dimmed" mt={2}>
						(0: other land cover, 1: temporary crops, 255: no data)
					</Text>
				</List.Item>
				<List.Item>
					<Text span fw={600}>
						cropland-postprocessed.tif
					</Text>
					<br />
					The final temporary crops mask after spatial cleaning of the raw result.
					<br />
					<Text size="sm" c="dimmed" mt={2}>
						(0: other land cover, 1: temporary crops, 255: no data)
					</Text>
				</List.Item>
				<List.Item>
					<Text span fw={600}>
						croptype-raw.tif
					</Text>
					<br />
					The original crop type map, generated by the user's custom crop type model.
					<br />
					The crop type model is only applied to the temporary crops pixels.
					<br />
					<Text size="sm" c="dimmed" mt={2}>
						(labels according to the user's custom model, 254: no temporary crops, 65535: no data)
					</Text>
				</List.Item>
				<List.Item>
					<Text span fw={600}>
						croptype-postprocessed.tif
					</Text>
					<br />
					The final crop type map after spatial cleaning of the raw result.
					<br />
					<Text size="sm" c="dimmed" mt={2}>
						(labels according to the user's custom model, 254: no temporary crops, 65535: no data)
					</Text>
				</List.Item>
			</List>
		</Stack>
	);
};

export default ProductResultsInfo;
